### PR TITLE
Fix: add scale context to slider start and end labels (fixes #82)

### LINKED ISSUE #82: associate start and end labels with the relevant scale value
Issue raised by external auditor and includes the following:

**Current behaviour:**
The scale labels “Confident” and “Not confident” (`labelStart`  and `labelEnd`) are read out as a single paragraph as the user moves through the page text and are not associated with the numbers on the scale. They are also coded incorrectly, using a mix of the `<label>` tag and `aria-label` attributes.

**Expected behaviour:**
The labels should refer to their related values, so a user navigating to these would hear e.g. “Confident, 1” and “Not confident, 10”. Users should be able to exit the slider control with the up arrow to hear these additional labels without needing to know advanced screen reader commands.

**Recommended fix**
Remove the `<label>` tags and `aria-label` attributes from the slider labels (“incomplete”/”complete”) and include visually-hidden text labels alongside the visible text to show the rating that relates to each label.

### PR DESCRIPTION
**Pull request by kirsty-hames**
- Remove `aria-label` attribute (this was replacing `labelStart` and `labelEnd` when reading)
- Add `aria-label span` containing scale context (distinguish start or end of scale and scale value). This is read alongside `labelStart` and `labelEnd`.
- Fix schema label error. Global defaults was setting both `labelStart` and `labelEnd` as '1'. Labels updated as per Slider schema for consistency.

How `slider__label-start` should now read:
'Start of the scale, 1, incomplete'

How `slider__label-end` should now read:
'End of the scale, 10, complete'

Issue already addressed in Slider https://github.com/adaptlearning/adapt-contrib-slider/pull/176

### CODE REVIEW

**Review by joe-allen-89 — CHANGES_REQUESTED** [review]
For some reason the labelStart and labelEnd are missing from the new style schemas, so we will need to add them to course.schema. I have double checked and it's definitely in slider already. 

`"labelStart": {
  "type": "string",
  "title": "Scale start ARIA label",
  "default": "Start of the scale",
  "_adapt": {
    "translatable": true
  }
  },
  "labelEnd": {
  "type": "string",
  "title": "Scale end ARIA label",
  "default": "End of the scale",
  "_adapt": {
    "translatable": true
    }
  }`

**Comment by joe-allen-89** [comment]
> > For some reason the labelStart and labelEnd are missing from the new style schemas, so we will need to add them to course.schema. I have double checked and it's definitely in slider already.
> > `"labelStart": { "type": "string", "title": "Scale start ARIA label", "default": "Start of the scale", "_adapt": { "translatable": true } }, "labelEnd": { "type": "string", "title": "Scale end ARIA label", "default": "End of the scale", "_adapt": { "translatable": true } }`
> 
> Thanks @joe-allen-89. When comparing slider and confidenceSlider _course.schema_ I've also noticed the slider `ariaRegion` is nested under [_components](https://github.com/adaptlearning/adapt-contrib-slider/blob/a71696d5d72fdbf5e5b5b16fd358d3e1617f5687/schema/course.schema.json#L15) but [confidenceSlider isn't](https://github.com/adaptlearning/adapt-contrib-confidenceSlider/blob/issue/82/schema/course.schema.json).
> 
> Should confidenceSlider be nested under `_components` too?

@kirsty-hames the confidence slider nesting in a _components object was released yesterday, was slightly delayed compared to slider being released - https://github.com/adaptlearning/adapt-contrib-confidenceSlider/releases/tag/v5.4.1

**Review by joe-allen-89 — APPROVED** [review]
Tested locally and with AAT, working nicely with both.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
